# Generated by Django 3.2.15 on 2022-09-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('total_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('name_uk', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('user_cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.cart')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_uk', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200, verbose_name='Продукт')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.заказ')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
