# Generated by Django 3.2.4 on 2021-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shopcart_продукт'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('usd_to_uah', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shop_currency',
                'managed': False,
            },
        ),
    ]
