# Generated by Django 3.2.15 on 2022-09-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_cart_usercart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usercart',
            options={'managed': False},
        ),
    ]
