# Generated by Django 3.2.4 on 2021-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shopcurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Заказ',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('фамилия', models.CharField(max_length=45)),
                ('имя', models.CharField(max_length=45)),
                ('отчество', models.CharField(blank=True, max_length=45, null=True)),
                ('телефон', models.CharField(blank=True, max_length=45, null=True)),
                ('почта', models.CharField(max_length=60)),
                ('заказ', models.TextField(blank=True, max_length=10000, null=True)),
                ('сумма_заказа', models.CharField(blank=True, max_length=45, null=True)),
                ('валюта_заказа', models.CharField(blank=True, max_length=45, null=True)),
                ('статус_оплаты', models.CharField(blank=True, choices=[('p', 'Оплачено'), ('np', 'Не оплачено')], default='np', max_length=45)),
                ('статус_заказа', models.CharField(blank=True, choices=[('d', 'Исполнено'), ('nd', 'Не исполнено')], default='nd', max_length=45, verbose_name='Статус Заказа')),
                ('дата_заказа', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Id пользователя')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом')),
                ('payment_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип оплаты')),
                ('delivery_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип доставки')),
                ('nova_pochta', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отделение Новой Почты')),
                ('ukr_pochta', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Индекс почтового отеделния')),
                ('confirm', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'db_table': 'shop_order',
                'managed': False,
            },
        ),
    ]
