# Generated by Django 3.2.7 on 2021-09-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_заказ'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFavourite',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('favourite_item', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=45, null=True)),
                ('currency', models.CharField(blank=True, max_length=45, null=True)),
                ('ru_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'shop_favourite',
            },
        ),
    ]
