# Generated by Django 3.2.15 on 2022-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220906_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
        migrations.DeleteModel(
            name='UserCartItem',
        ),
    ]
