# Generated by Django 3.2.7 on 2021-09-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shopfavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfavourite',
            name='uk_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
