# Generated by Django 3.2.7 on 2021-09-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shopfavourite_uk_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopfavourite',
            options={'managed': True},
        ),
    ]
