# Generated by Django 3.2.7 on 2021-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_shopfavourite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfavourite',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
