# Generated by Django 3.2.15 on 2022-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(blank=True, default='₴', max_length=5, null=True),
        ),
    ]
