# Generated by Django 3.2.15 on 2022-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_orderitem_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='currency',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (в UAH)'),
        ),
    ]
