# Generated by Django 3.2.15 on 2022-09-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220907_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
