# Generated by Django 3.2.15 on 2022-09-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220907_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True, 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
