# Generated by Django 3.2.15 on 2022-09-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_orderitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
    ]
