# Generated by Django 3.2 on 2021-06-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210426_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Заказ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('фамилия', models.CharField(max_length=45)),
                ('имя', models.CharField(max_length=45)),
                ('отчество', models.CharField(blank=True, max_length=45, null=True)),
                ('телефон', models.CharField(blank=True, max_length=45, null=True)),
                ('почта', models.CharField(max_length=45)),
                ('заказ', models.CharField(max_length=120)),
                ('сумма_заказа', models.IntegerField(db_column='сумма заказа')),
                ('валюта_заказа', models.CharField(db_column='валюта заказа', default='UAH', max_length=5)),
                ('дата_заказа', models.DateTimeField(db_column='дата заказа')),
                ('адрес', models.CharField(db_column='Адрес', max_length=100)),
                ('статус_заказа', models.CharField(choices=[('d', 'Исполнено'), ('nd', 'Не исполнено')], db_column='статус заказа', default='Не исполнено', max_length=45)),
                ('статус_оплаты', models.CharField(db_column='статус оплаты', default='Не оплачено', max_length=45)),
                ('общая_сумма_заказов', models.IntegerField(db_column='общая сумма заказов', default=0)),
                ('общая_сумма_заказов_валюта', models.IntegerField(db_column='общая сумма заказов валюта', default=0)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'db_table': 'shop_order',
                'managed': False,
            },
        ),
    ]
