# Generated by Django 3.2.4 on 2021-08-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210809_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcalls',
            name='timedate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания запроса'),
        ),
        migrations.AlterField(
            model_name='продукт',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='продукт',
            name='валюта',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('UAH', 'UAH')], db_column='Валюта', max_length=3, null=True),
        ),
    ]
