# Generated by Django 3.2.15 on 2022-09-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderitem_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
