# Generated by Django 3.2.4 on 2021-06-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_заказ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Клиент',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('имя', models.CharField(db_column='имя', max_length=90)),
                ('фамилия', models.CharField(db_column='фамилия', max_length=90)),
                ('отчество', models.CharField(db_column='отчество', max_length=90)),
                ('телефон', models.CharField(db_column='телефон', max_length=45)),
                ('почта', models.CharField(db_column='почта', max_length=254)),
                ('пароль', models.CharField(db_column='пароль', default='12345', max_length=150)),
                ('адрес', models.CharField(db_column='адресс', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'db_table': 'shop_client',
                'managed': False,
            },
        ),
    ]
