# Generated by Django 3.2.4 on 2021-08-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210809_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукт',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='продукт',
            name='цена',
            field=models.FloatField(blank=True, db_column='Цена', null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='shop.продукт')),
            ],
        ),
    ]
