# Generated by Django 3.2.4 on 2021-06-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_клиент'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Клиент',
        ),
    ]
