# Generated by Django 3.2.4 on 2021-08-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210813_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='productInfo/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.продукт'),
        ),
        migrations.AlterField(
            model_name='продукт',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='продукт',
            name='единица_измерения',
            field=models.CharField(blank=True, choices=[('шт.', 'шт.')], db_column='Единица_измерения', max_length=8, null=True),
        ),
    ]
