# Generated by Django 3.2.6 on 2021-08-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210813_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcalls',
            name='viewed_product',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Просматриваемый продукт'),
        ),
    ]
