# Generated by Django 3.2.15 on 2022-09-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': False, 'verbose_name_plural': 'Продукты'},
        ),
    ]
