# Generated by Django 3.2.6 on 2021-08-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shopcalls_viewed_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcalls',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена'),
        ),
    ]
