# Generated by Django 3.2.6 on 2021-08-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shopcalls_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='продукт',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='shopcalls',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цена продукта'),
        ),
    ]
