# Generated by Django 3.2.15 on 2022-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220906_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usercartitem',
            options={'managed': True},
        ),
    ]
