# Generated by Django 3.2.6 on 2021-08-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_продукт_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукт',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название позиции англ'),
        ),
    ]
