# Generated by Django 3.2.15 on 2022-09-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220906_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
        migrations.DeleteModel(
            name='UserCartItem',
        ),
    ]
