# Generated by Django 3.2.6 on 2021-08-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_продукт_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукт',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
