# Generated by Django 3.2.6 on 2021-08-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_продукт_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='item_en',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='item_uk',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
