# Generated by Django 3.2.15 on 2022-09-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_usercart_usercartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
