# Generated by Django 3.2.15 on 2022-09-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_delete_usercart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
    ]
