# Generated by Django 3.2.6 on 2021-08-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210830_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='заказ',
            name='raworder',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Заказ'),
        ),
    ]
