# Generated by Django 3.2.6 on 2021-08-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_заказ_raworder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='заказ',
            name='raworder',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Заказ'),
        ),
    ]
