# Generated by Django 3.2.15 on 2022-09-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_authuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCartItem',
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': False, 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
