# Generated by Django 3.2.15 on 2022-09-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220907_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Заказ',
            new_name='Orders',
        ),
        migrations.RenameModel(
            old_name='Продукт',
            new_name='Products',
        ),
    ]
