# Generated by Django 3.2.6 on 2021-08-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_заказ_raworder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='item_en',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='item_uk',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='admin_order_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
