# Generated by Django 3.2.6 on 2021-08-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210831_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='заказ',
            old_name='raworder',
            new_name='order_ru',
        ),
        migrations.AddField(
            model_name='заказ',
            name='order_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='заказ',
            name='order_uk',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
