# Generated by Django 3.2.15 on 2022-09-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20220907_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': False, 'verbose_name': b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb4\xd1\x83\xd0\xba\xd1\x82', 'verbose_name_plural': b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb4\xd1\x83\xd0\xba\xd1\x82\xd1\x8b'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': b'\xd0\x97\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7', 'verbose_name_plural': b'\xd0\x97\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7\xd1\x8b'},
        ),
    ]
