# Generated by Django 3.2.15 on 2022-09-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20220907_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': False, 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
