# Generated by Django 3.2.6 on 2021-08-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210831_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='admin_order_item',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='en_order_item',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='ru_order_item',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='uk_order_item',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
