# Generated by Django 3.2.7 on 2021-09-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210831_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название категории')),
                ('category_id', models.CharField(blank=True, max_length=300, null=True)),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'shop_category',
            },
        ),
        migrations.RemoveField(
            model_name='продукт',
            name='название_группы',
        ),
        migrations.AddField(
            model_name='продукт',
            name='категория',
            field=models.ForeignKey(blank=True, db_column='Название_группы', max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shopcategory'),
        ),
    ]
