# Generated by Django 3.2.7 on 2021-09-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20210913_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcategory',
            name='category_name',
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='category_name_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='category_name_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название на русском'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='category_name_uk',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название на украинском'),
        ),
    ]
