# Generated by Django 3.2.15 on 2022-09-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_orders_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
