# Generated by Django 3.2.7 on 2021-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210913_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='category_id',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Id категории'),
        ),
        migrations.AlterField(
            model_name='продукт',
            name='категория',
            field=models.CharField(blank=True, db_column='Название_группы', max_length=100, null=True),
        ),
    ]
