# Generated by Django 3.2.7 on 2021-09-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210913_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукт',
            name='категория',
            field=models.ForeignKey(blank=True, db_column='Название_группы', max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shopcategory'),
        ),
    ]
