# Generated by Django 3.2.7 on 2021-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_продукт_категория'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукт',
            name='категория',
            field=models.CharField(blank=True, db_column='Название_группы', max_length=100, null=True),
        ),
    ]
