# Generated by Django 3.2.7 on 2021-09-19 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20210919_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукт',
            name='скидка',
            field=models.IntegerField(blank=True, db_column='Скидка', default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Скидка (%)'),
        ),
    ]
