# Generated by Django 3.2.7 on 2021-09-19 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_продукт_скидка'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукт',
            name='минимальный_заказ_опт',
            field=models.IntegerField(blank=True, db_column='Минимальный_заказ_опт', null=True),
        ),
        migrations.AlterField(
            model_name='продукт',
            name='скидка',
            field=models.IntegerField(blank=True, db_column='Скидка', default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Скидка (%)'),
        ),
    ]
