# Generated by Django 3.2.7 on 2021-09-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20210919_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='продукт',
            name='минимальный_объем_заказа',
            field=models.IntegerField(blank=True, db_column='Минимальный_объем_заказа', null=True),
        ),
    ]
