# Generated by Django 4.0.1 on 2022-01-13 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_продукт_минимальный_объем_заказа'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name_ru', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название на русском')),
                ('subcategory_name_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название на английском')),
                ('subcategory_name_uk', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название на украинском')),
                ('subcategory_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='Id категории')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table': 'shop_subcategory',
            },
        ),
        migrations.RemoveField(
            model_name='shopcategory',
            name='category_description',
        ),
        migrations.RemoveField(
            model_name='продукт',
            name='категория',
        ),
        migrations.AlterField(
            model_name='продукт',
            name='скидка',
            field=models.IntegerField(db_column='Скидка', default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='категория',
            field=models.ForeignKey(blank=True, db_column='Название_подгруппы', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopsubcategory'),
        ),
    ]
