# Generated by Django 4.0.1 on 2022-01-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_shopsubcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcategory',
            name='категория',
        ),
        migrations.AddField(
            model_name='shopsubcategory',
            name='подкатегория',
            field=models.ForeignKey(blank=True, db_column='Название_подгруппы', max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopcategory'),
        ),
    ]
