# Generated by Django 4.0.1 on 2022-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_remove_shopcategory_категория_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='shopsubcategory',
            name='подкатегория',
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='подкатегория',
            field=models.ManyToManyField(to='shop.ShopSubCategory'),
        ),
        migrations.AlterField(
            model_name='shopsubcategory',
            name='subcategory_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Id подкатегории'),
        ),
    ]
