# Generated by Django 4.0.1 on 2022-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_shopcategory_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
