# Generated by Django 4.0.1 on 2022-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_продукт_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='заказ',
            name='comment',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
    ]
