# Generated by Django 4.0.1 on 2022-07-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_заказ_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='заказ',
            name='comment',
        ),
    ]
